blog/views/auth.py
from sqlite3 import IntegrityError
from flask import Blueprint, redirect, url_for, render_template, request, current_app
from flask_login import LoginManager, login_user, logout_user, login_required, current_user
from werkzeug.exceptions import NotFound

from blog.forms.user import RegisterForm, LoginForm
from blog.models import User
from blog.models.database import db

auth = Blueprint('auth', __name__, url_prefix='/auth', static_folder='../static')


login_manager = LoginManager()
login_manager.login_view = 'auth.login'


def login():
    return "WIP"
# if request.method == "GET":
# return render_template("auth/login.html")
#
#
# login_user(user)
# return redirect(url_for("index"))


@auth.route("/login-as/", methods=["GET", "POST"], endpoint="login-as")
def login_as():
    if not (current_user.is_authenticated and current_user.is_staff):
        # non-admin users should not know about this feature
        raise NotFound
    if request.method == 'GET':
        return render_template('auth/login-as.html')

    username = request.form.get('username')
    if not username:
        return render_template('auth/login-as.html', error='username nit passed')

    user = User.query.filter_by(username=username).one_or_none()
    if user is None:
        return render_template('auth/login-as.html', error=f'no user {username!r} found')

    login_user(user)
    return redirect(url_for('index.index'))


@auth.route('/register/', methods=['GET', 'POST'], endpoint='register')
def register():
    if current_user.is_authenticated:
        return redirect(url_for('index.index'))

    error = None
    form = RegisterForm(request.form)

    if request.method == "POST" and form.validate_on_submit():
        if User.query.filter_by(username=form.username.data).count():
            form.username.errors.append("username already exists!")
            return render_template("auth/register.html", form=form)

        if User.query.filter_by(email=form.email.data).count():
            form.email.errors.append("email already exists!")
            return render_template("auth/register.html", form=form)

        user = User(
            first_name=form.first_name.data,
            last_name=form.last_name.data,
            username=form.username.data,
            email=form.email.data,
            is_staff = False,
        )
        user.password = form.password.data
        db.session.add(user)

        try:
            db.session.commit()
        except IntegrityError:
            current_app.logger.exeption("Could not create user!")
            error = "Could not create user!"
        else:
            current_app.logger.info("User created %s", user)
            login_user(user)
            return redirect(url_for('index.index'))

    return render_template('auth/register.html', form=form, error=error)

@login_manager.user_loader
def load_user(user_id):
    return User.query.filter_by(id=user_id).one_or_none()


@login_manager.unauthorized_handler
def unauthorized():
    return redirect(url_for('auth.login'))


@auth.route('/login/', methods=['GET', 'POST'], endpoint='login')
def login():
    if current_user.is_authenticated:
        return redirect(url_for('index.index'))

    form = LoginForm(request.form)

    if request.method == 'POST' and form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).one_or_none()

        if user is None:
            return render_template('auth/login.html', form=form, error='username does not exist!')

        if not user.validate_password(form.password.data):
            return render_template('auth/login.html', form=form, error='invalid username or password!')

        login_user(user)
        return redirect(url_for('index.index'))

    return render_template('auth/login.html', form=form)



@auth.route('/logout', endpoint='logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('index.index'))


@auth.route("/secret/")
@login_required
def secret_view():
    return "Super secret data"


__all__ = [
    'login_manager',
    'auth',
]

blog/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">



    <!-- Bootstrap CSS -->
    <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">

    <title>{% block title %}Base{% endblock %}</title>
  </head>
  <body>

{% include 'navbar.html' %}

<div class="container">
  {% block body %}
  <div>
    <h1>Hello, world!</h1>
  </div>
  {% endblock %}
</div>

    {% block js %}
    {{ moment.include_moment() }}

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="{{ url_for('static', filename='js/bootstrap.bundle.min.js') }}"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
  {% endblock %}
  </body>
</html>

blog/templates/index.html
{% extends 'base.html' %}

{% block title %}
Index page
{% endblock %}

{% block body %}

<h1>
    Hello
    {% if current_user.is_authenticated %}
        {{ current_user.username }}
    {% else %}
        anon
    {% endif %}
</h1>


{% endblock %}

blog/templates/navbar.html
<!--  {# nav bar #}-->
<nav class="navbar navbar-expand-md navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="{{ url_for('index.index') }}">Blog</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                {% for (endpoint, label) in [('user_app.list', 'Users'),
                ('articles.list', 'Articles'), ('authors_app.list', 'Authors')] %}
                <a href="{{ url_for(endpoint) }}"
                   class="nav-link {% if request.endpoint == endpoint -%}active{%- endif %}"
                >
                    {{ label }}
                </a>
                {% endfor %}
            </div>

            <div class="navbar-nav ms-auto">
                {% if current_user.is_authenticated %}
                <a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
                {% else %}
                <a class="nav-link" href="{{ url_for('auth.register') }}">Register</a>
                <a href="{{ url_for('auth.login') }}"
                   class="nav-link {% if request.endpoint == 'login' -%}active{%- endif %}">
                    Login
                </a>
                {% endif %}
            </div>


        </div>
    </div>
</nav>